spring:
  jackson:
    default-property-inclusion: non_null
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:./db/springchallenge.db
    username: sa
    password: sa