spring:
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:connection:string
    username: user
    password: pass